### ISSUE TITLE
Error in Plugin and xournalpp crash 

### ISSUE THREAD

**Issue by andrelkin** [raw-bacon/vi-xournalpp#18]
Hello.

First off, this is a great idea which so many users would love to see realized :1st_place_medal: ! Thank you!!!

I installed the plugin having 1.1.0+dev xournal++ <details>
<summary>Details</summary>
$ xournalpp --version
Xournal++ 1.1.0+dev 
└──libgtk: 3.22.30 

</details>

on my Ubuntu 18.04 with installed lua50.
The plugin was enabled 

<details>
<summary>Details</summary>

** Message: 15:51:10.122 : Plugin «vi-xournalpp» UI initialized

</details>

but I could not make any key to work.

E.g pressing `c` led to
```
** (com.github.xournalpp.xournalpp:23122): WARNING **: 15:51:14.364: Error in Plugin: «vi-xournalpp», error: «/usr/bin/../share/xournalpp//plugins/vi-xournalpp/api.lua:101: attempt to call a nil value (field 'changeToolColor')»
```
Pressing `w` led to a straight crash
```
** (com.github.xournalpp.xournalpp:28889): ERROR **: 16:06:33.009: Invalid enum value for ActionType: «ACTION_TOOL_DRAW_ELLIPSE»
Trace/breakpoint trap (core dumped)

```
It feels a configuration issue, like versions of `lua` or `xournal++`. 
**BUT** `Example` plugin works fine.

Any feedback would be greatly appreciated.

Andrei

**Comment by raw-bacon** [comment]
Hi, thank you very much.

This seems like the same kinds of error that running the plugin on 1.0.x throws, which is due to changes in the API changing from version 1.0.x to 1.1.x. Perhaps in the version of the development branch you're running, these changes were not yet applied.

Confirming this suspicion would require you to run the 1.0.x branch of this plugin (which is considerably less powerful, sadly) and see if the errors persist. Could you try this and report back?

Levi

**Comment by andrelkin** [comment]
Sure, I will shortly check 1.0.x and tell you.

**Comment by andrelkin** [comment]
Tested 1.0.20 to reproduce 

```
** (com.github.xournalpp.xournalpp:9349): WARNING **: 22:26:36.040: Error in Plugin: «vi-xournalpp», error: «/usr/bin/../share/xournalpp//plugins/vi-xournalpp/api.lua:101: attempt to call a nil value (field 'changeToolColor')»

```
through both the hotkeys and plugin menu in which the hotkeys are listed (something that I did not expect with 10.1 either).

**Comment by raw-bacon** [comment]
Hi Andrei,

Sorry for getting back to you so late, I missed the second notification.

In case you are still interested in diagnosing this, I meant running the 1.0.x branch of _this plugin_ on a 1.0.x version of Xournal++. Alternatively, run a 1.1.x release (rather than an old dev version) and try the main branch :)

Best,
Levi

**Comment by andrelkin** [comment]
Salute Levi!

I have a good news Xournal++ 1.1.0 works with the plugin 1.0.x as expected.
Thank you for the hints!

Looking forward to upgrade the plugin, and hopefully to contribute to it :-)!

Cheers,

Andrei

**Comment by raw-bacon** [comment]
Hi Andrei,

Great, that's good to hear :)

What OS / distro are you on? Do you have a way to switch to the current version of Xournal++?  I suspect that this will make you able to use the main branch of the plugin.

Have a good one,
Levi

**Comment by andrelkin** [comment]
I am still on Ubuntu 18.04 which does not let to build the most recent Xournal++. I've found  `xournalpp-1.1.2-x86_64.AppImage` which starts but I am to learn whether/how I can install your plugin in there...

**Comment by andrelkin** [comment]
>  Do you have a way to switch to the current version of Xournal++? I suspect that this will make you able to use the main branch of the plugin.

Finally it's all up-to-date! `https://xournalpp.github.io` provides nightly builds for my retarded ubuntu version as well. 
Cheers!!!

**Comment by raw-bacon** [comment]
Great to hear that you managed to get it to work. Shall we close the issue? :)

**Comment by andrelkin** [comment]
Thank you Levi for the help!
